package com.autoremix.djslow.logchat

import android.content.Context
import androidx.test.core.app.ApplicationProvider
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import java.io.File
import java.io.PrintWriter
import java.io.StringWriter

@RunWith(RobolectricTestRunner::class)
class LogChatManagerTest {

    private lateinit var context: Context

    @Before
    fun setup() {
        context = ApplicationProvider.getApplicationContext()
        LogChatManager.init(context)
        LogChatManager.clearLogs()
    }

    @Test
    fun testClearLogsLeavesZeroLogsAndNoAutoGeneratedEntry() = runBlocking {
        LogChatManager.info(LogModule.SYSTEM, "Test event 1")
        LogChatManager.info(LogModule.AUDIO, "Test event 2")
        assertEquals(2, LogChatManager.logs.value.size)

        // Clear logs
        LogChatManager.clearLogs()

        // Harus 0 log, TIDAK boleh ada log baru "Seluruh catatan LogChat berhasil dibersihkan..."
        assertEquals(0, LogChatManager.logs.value.size)

        // Verifikasi file crash dan log terhapus
        val crashFile = File(context.filesDir, "logchat/last_crash.txt")
        val logFile = File(context.filesDir, "logchat/logchat_history.json")
        assertTrue(!crashFile.exists())
    }

    @Test
    fun testConcurrentLoggingUnderLoad() = runBlocking {
        // Uji ratusan event paralel dari thread berbeda untuk memastikan kestabilan
        val jobs = (1..50).map { i ->
            async(Dispatchers.Default) {
                LogChatManager.info(
                    module = if (i % 2 == 0) LogModule.AUDIO else LogModule.REMIX,
                    message = "Concurrent event $i",
                    detail = "Detail payload for event $i",
                    stage = "STAGE_$i"
                )
            }
        }
        jobs.awaitAll()

        val logs = LogChatManager.logs.value
        assertEquals(50, logs.size)
        // Pastikan tidak ada duplikasi ID
        val uniqueIds = logs.map { it.id }.toSet()
        assertEquals(50, uniqueIds.size)
    }

    @Test
    fun testPipelineStatusTransitions() {
        LogChatManager.updatePipeline(PipelineStage.INPUT, StepStatus.WARNING, "Reading input...")
        assertEquals(StepStatus.WARNING, LogChatManager.pipelineStatus.value[PipelineStage.INPUT]?.status)

        LogChatManager.updatePipeline(PipelineStage.INPUT, StepStatus.SUCCESS, "Input verified")
        assertEquals(StepStatus.SUCCESS, LogChatManager.pipelineStatus.value[PipelineStage.INPUT]?.status)
        assertEquals("Input verified", LogChatManager.pipelineStatus.value[PipelineStage.INPUT]?.detail)
    }

    @Test
    fun testCrashHandlerCapturesExceptionAndForwards() {
        var defaultHandlerCalled = false
        val mockDefaultHandler = Thread.UncaughtExceptionHandler { _, _ ->
            defaultHandlerCalled = true
        }

        val handler = CrashHandler(context, mockDefaultHandler)
        val dummyException = RuntimeException("Uji CrashHandler Unit Test")

        handler.uncaughtException(Thread.currentThread(), dummyException)

        // Pastikan default handler tetap dipanggil (tidak menelan crash)
        assertTrue(defaultHandlerCalled)

        // Pastikan file last_crash.txt terbentuk
        val crashFile = File(context.filesDir, "logchat/last_crash.txt")
        assertTrue(crashFile.exists())
        val content = crashFile.readText()
        assertTrue(content.contains("Uji CrashHandler Unit Test"))
        assertTrue(content.contains("THREAD:"))
    }
}
